trading_instruments:
  active:
    symbol: "MESU4" # Replace with the actual symbol for active  "MESZ24.CME" or "MES=F"? 
    type: "STK"
    currency: USD
    exchange: "SMART"
    LastTradeDateOrContractMonth: '202409'
  passive:
    symbol: "SHY" # SHY
    type: "STK"
    currency: USD
    exchange: SMART


ACC_IDs:
  ID_1: "U13254634"
  
